frameworkVersion: ">=1.2.1"

service: flag-lambda

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-2

functions:
  predict:
    handler: handler.predict
    events:
      - http:
          path: /predict
          method: get

